name: Check Links

on:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check links in README.md
      uses: lycheeverse/lychee-action@v1.9.3
      with:
        args: ./README2.md
