name: CI

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Run Hello World Action from the same repository
    - name: Run Hello World Action
      uses: ./hello-world-action # Uses an action in the hello-world-action directory
      with:
        name: 'Timothy'

    # Example of referencing a custom action from another repository
    # - name: Run Another Custom Action
    #   uses: timothywarner-org/another-repo@v1
    #   with:
    #     name: 'Example'
